# This file may be used to create an environment using:
# $ conda env create --file <this file>
name: hawaiian-pronunciation
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - pip:
    - pytest

